version: '3'
services:
    #PHP Service
    pxl_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: pxl_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: pxl_app
            SERVICE_TAGS: dev
            DB_HOST : pxl_db
        working_dir: /var/www
        depends_on:
            - pxl_db
        volumes:
            - ./:/var/www
        networks:
            - app-network

    #Nginx Service
    pxl_server:
        image: nginx:alpine
        container_name: pxl_server
        restart: unless-stopped
        tty: true
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    pxl_db:
        image: 'mysql:8.0'
        container_name: pxl_db
        restart: unless-stopped
        tty: true
        ports:
            - "5306:3306"
        environment:
            MYSQL_DATABASE: pxl_db
            DB_USERNAME: pxl
            DB_PASSWORD: pxl.
            MYSQL_ROOT_PASSWORD: pxl.
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        #- dbdata:/var/lib/mysql/
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
    redisdata:
        driver: local
